-- Rename to ae2colony_config.lua on the computer (same folder as ae2Colony.lua).
-- Must return a table. Keys you omit keep script defaults.

return {
  exportSide = "top",
  exportChestPeripheral = nil,
  exportLedgerFile = "ae2colony_export_ledger.json",
  scanInterval = 30,
  colonyUiInterval = 5,
  showConstructionDetail = true,
  showConstructionNeedsList = true,
  constructionNeedsMaxWorkOrders = 3,
  constructionNeedsMaxItems = 14,
  showConstructionPushFooter = true,
  mergeBuilderHutResources = true,
  constructionNeedDuplicateMerge = "max",
  constructionNeedsHideNotNeeded = true,
  constructionPushDrainAfterCraft = true,
  constructionPushDrainPollSeconds = 1,
  constructionPushDrainTimeoutSeconds = 180,
  constructionPushDrainMaxPerTick = 4,
  showMeCraftingStatus = true,
  showMeCraftingSpinner = true,
  -- Third monitor line (height >= 8): last craft orders, export bar, CPU hint.
  showMeCraftingHudLine = true,
  -- Optional: prepend [NEEDS] + / - / ~ lines when the material list changes (see docs/ALERTS.md).
  showConstructionNeedsDiff = false,
  constructionNeedsDiffMaxLines = 4,
  pinnedAlertsMaxLines = 3,
  -- Experimental: split monitor (needs scada.enabled + wide monitor). See docs/SCADA.md
  -- uiMode = "classic",
  -- ui = { mode = "scada" },
  -- scada = {
  --   enabled = true,
  --   intervalSec = 15,
  --   minMonitorWidth = 26,
  --   leftBodyFraction = 0.58,
  --   saturationWarnBelow = 8,
  --   scanMeFoodFromWhitelist = true,
  --   foodWhitelist = { "minecraft:bread", "minecraft:cooked_beef" },
  --   historyFile = "ae2colony_scada_history.jsonl",
  --   historySampleSec = 60,
  --   maxHistoryPoints = 48,
  --   trendWindowPoints = 10,
  --   warnTrendDropCycles = 3,
  -- },
  -- Speaker + redstone alerts (debounced). Off by default.
  alerts = {
    enabled = false,
    minIntervalSec = 10,
    useSpeaker = true,
    speakerPeripheralName = nil,
    useRedstone = false,
    redstoneSide = "back",
    redstonePulseTicks = 2,
    onRaid = true,
    onMeOffline = true,
    onMeOnline = false,
    onMissingPattern = true,
    onPostCraftTimeout = true,
    onGetBuildingsBreaker = true,
    onColonyRequestsCritical = true,
    onCraftStarted = false,
  },
  -- Bottom-right mute chip when alerts.enabled (v0.5.15+).
  showAlertsMuteButton = true,
  showBuildingsList = false,
  buildingsBreakerMinutes = 30,
  maxLinesPerGroup = 12,
  monitorGroupOrder = {
    "COLONY",
    "NEEDS",
    "WARN",
    "ERROR",
    "MISSING",
    "CRAFT",
    "SENT",
    "MANUAL",
    "INFO",
  },
  craftMaxStack = false,
  doLog = false,
  doLogExtra = false,
  -- missingPatternHook = { enabled = false, httpUrl = nil, httpSecret = nil },
}
